# Generated by Django 2.0.7 on 2018-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='peg_1',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='peg_2',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='peg_3',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='peg_4',
            field=models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1, null=True),
        ),
    ]
