# Generated by Django 2.0.7 on 2018-07-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_auto_20180706_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peg_1', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1)),
                ('peg_2', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1)),
                ('peg_3', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1)),
                ('peg_4', models.CharField(blank=True, choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow')], max_length=1)),
                ('guess_number', models.IntegerField(default=0)),
                ('black_pegs', models.IntegerField(default=0)),
                ('white_pegs', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.Game')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
